### ISSUE TITLE
Could you publish tq on pypi ?

### ISSUE THREAD

**Issue by Lucas-C** [plainas/tq#12]
Hi,

I find `tq` quite useful, could you maybe publish it on pypi.org ?

Regards.

**Comment by plainas** [comment]
Hey Lucas,
glad you find this useful.

I do not intend to do that myself, simply because I am too lazy to update yet another repository. In all honesty, that would result in an abandoned package. Not that this repo gets a whole lot of activity, but I do read the issues and will merge any pull request of value.

But by all means,  you, or any well intentioned person, are very welcome to publish and maintain this on pypi. I encourage it. You can even do it from your own fork if that is easier for you. Or if you have any reason to do so.

tq is only a tiny 50 lines of icing on top beautifulsoup, which in its turn is, AFAIK, api swetness built on lxml. Virtually any python developer is technically capable of maintaining such a codebase as it as small and simple as it gets.

BR

**Comment by Lucas-C** [comment]
Ok, I understand.
If I start tu use it intensely, I may indeed fork it.
Anyway, thanks for the answser.
